name: Auto Merge Pull Requests

# To disable automerge, simply remove this label from secrets

on:
    workflow_run:
        types:
            - completed
        workflows:
            - 'Create content file'
    pull_request:
        types:
            - opened
            - labeled
    workflow_dispatch:

jobs:
    automerge:
        runs-on: ubuntu-latest
        steps:
            - name: merge
              uses: FelippeChemello/merge-bot@v0.4.8
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  reviewers: false
                  blocking_labels: do not merge
                  method: squash
                  delete_source_branch: false
                  authors: github-actions[bot],dependabot[bot]
