name: Build and Publish CLI

on:
    push:
        branches:
            - master
        paths:
            - 'src/**'
            - 'video/**'
            - 'assets/**'
    workflow_dispatch:

jobs:
    CacheDependencies:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.JS environment
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Cache node_modules
              id: dependencies
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

            - name: Install project dependencies
              if: steps.dependencies.outputs.cache-hit != 'true'
              run: yarn

    BuildAndPublish:
        needs: [CacheDependencies]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.JS environment
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  always-auth: true

            - name: Get node_modules from cache
              id: dependencies
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

            - name: Install project dependencies
              if: steps.dependencies.outputs.cache-hit != 'true'
              run: yarn

            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  check-version: false
