name: Create content file

on:
    schedule:
        - cron: '20 14 * * 1-5'
    workflow_dispatch:

env:
    DEBUG: 1
    GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
    GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
    GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
    #  ACTIONS_RUNNER_DEBUG: true
    #  ACTIONS_STEP_DEBUG: true

jobs:
    CreateContentFile:
        needs: [CacheDependencies]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install CLI
              uses: FelippeChemello/action-npm-global@1.0.0
              with: 
                package-manager: 'yarn'
                package-name: podcast-maker

            - name: Create SymLink from content directory (on code) to content directory (created by podcast-maker CLI)
              run: |
                DataPath=$(podcast-maker info content --dir | sed -e "s/\/[^\/]*$//")
                ContentPath=$(podcast-maker info content --dir)
                if [ -d "$ContentPath" ]; then 
                    ls $ContentPath;
                    echo "ContentPath exists, deleting it"; 
                    rm -rf $ContentPath; 
                fi; 
                echo "Creating SymLink from $(pwd)/content to $DataPath"; 
                ln -s $(pwd)/content $DataPath                                   


            - name: Get current date
              id: date
              run: |
                  echo "::set-output name=formattedDate::$(date +%d/%m/%Y)"
                  echo "::set-output name=bashDate::$(date +%d-%m-%Y)"

            - name: Create Content File
              run: podcast-maker content mail

            - name: Create PR to master with Content File
              uses: peter-evans/create-pull-request@v3
              with:
                  title: Conteúdo ${{ steps.date.outputs.formattedDate }}
                  body: Automação - Conteúdo ${{ steps.date.outputs.formattedDate }}
                  branch: ${{ steps.date.outputs.formattedDate }}
                  commit-message: Conteúdo ${{ steps.date.outputs.formattedDate }}
                  labels: ${{ secrets.COMMIT_LABELS }}
                    
