name: Create video

on:
    push:
        branches: [master]
    workflow_dispatch:

env:
    DEBUG: ${{ secrets.DEBUG }}
    AZURE_TTS_KEY: ${{ secrets.AZURE_TTS_KEY }}
    AZURE_TTS_REGION: ${{ secrets.AZURE_TTS_REGION }}
    YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
    YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
    YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
    REBRANDLY_API_KEY: ${{ secrets.REBRANDLY_API_KEY }}

jobs:
    TextToSpeech:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.JS environment
              uses: actions/setup-node@v2.1.4
              with:
                  node-version: 14.x

            - name: Install project dependencies
              run: yarn

            - name: Create TTS
              run: yarn video:auto:tts

            - name: Save TTS files in Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: audio-files
                  path: tmp/*.mp3
                  retention-days: 3

    YouTubeVideo:
        needs: [TextToSpeech]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Download TTS files
              uses: actions/download-artifact@v2
              with:
                  name: audio-files
                  path: tmp/

            - name: Install project dependencies
              run: yarn

            - name: Create and Upload Youtube video
              run: yarn video:auto:youtube

            - name: Save video in Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: audio-files
                  path: tmp/*.mp4
                  retention-days: 2
