name: Create video

on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    TextToSpeech:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Upload TTS files
              uses: actions/upload-artifact@v2
              with:
                  name: audio-files
                  path: assets
                  retention-days: 5

    YouTubeVideo:
        needs: [TextToSpeech]
        runs-on: ubuntu-latest
        steps:
            - run: mkdir tmp
            - uses: actions/download-artifact@v2
              with:
                  name: audio-files
                  path: tmp/
            - run: unzip tmp/audio-files.zip
            - run: ls tmp
